### ISSUE TITLE
Remove buffering on stdout

### ISSUE THREAD

**Issue by maxux** [threefoldtech/zinit#15]
When reading logs from an application, stdout is buffered by default and make the logging not reliable. Here is a code example:
```
    for(int i = 0; i < 1024; i++) {
        printf("stdout %d\n", i);
        fprintf(stderr, "stderr %d\n", i);
        usleep(100000);
    }
```

Output of stderr is well received on the `log.sock` socket but stdout is dumped at random moment. This is the normal behavior but not reliable or useful when logging.

We should set stdout as buffered by line (`setvbuf(stdout, _IOLBF)`).

**Comment by muhamadazmy** [comment]
It's the daemons that buffers there stdout/stderr. why might be able to change our binaries to not have buffers on fd 1, and 2. but we can't do this for all other daemons that we have running

**Comment by maxux** [comment]
I guess zinit fork/exec subprocess no ? You can do it then.

**Comment by muhamadazmy** [comment]
@maxux you are right! i properly can fnctl the pipe before passing it to the child process

**Comment by maxux** [comment]
http://www.pixelbeat.org/programming/stdio_buffering/

**Comment by muhamadazmy** [comment]
This thing is more complicated than i thought. libc detects the typo of stdout of a program (if it's a pty or not) and based on that decides if using a lined buffer, or fully buffered. The app can still decided to change the stdout/stderr buffering pragmatically by doing calls to some libc methods (like `setvbuf`), which will override default libc detection.

Anyway, so the only way from our side `(zinit)` is to make the app think that is connected to a `tty` not a `pipe`.

Some utils already can do that (like unbuffer from expect package) and (stdbuf) utils. I am trying to read the code to understand what they do exactly and if we can replicate that in rust. 

A worst case is that we include the `stdbuf` util in the image and use it to exec services instead of exec-ing them directly.

**Comment by muhamadazmy** [comment]
The stdbuf uses a trick with a `LD_PRELOAD` to pre load a libstdbuf library that on loaded do the proper calls to stdvbuf. the proper modes are passed using some env variables set by the stdbuf executable.

It means we also can do the same if we have the libstdbuf.so on 0-initramfs image, and then set all LD_PRELOAD,  _STDBUF_O, and _STDBUD_E to correct values.

**Comment by muhamadazmy** [comment]
I also found this, well see if it's easier to use than stdbuf
https://github.com/uutils/coreutils/blob/master/src/stdbuf/stdbuf.rs

**Comment by maxux** [comment]
That's fine for me :)
