### ISSUE TITLE
Add restart command

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zinit#54]
Would like to:

```
zinit restart <service>
```

As essentially an alias for:

```
zinit stop <service> && zinit start <service>
```

**Comment by muhamadazmy** [comment]
It's not exactly a `1 to 1` mapping from zinit stop && zinit start because a restart command will need to wait until the service actually fully stop then start it again after wards (just saying). Stop on the other hand does not wait for the service to actually exit, instead it just sets the target to `down` so zinit does not start it again when it dies, then send a term signal (default) or whatever is configured in service unit file. Means there is still a chance the service does not actually die when u do `stop` it's up to the operator to check it (with status) and send a kill signal if needed. Since we tried to make zinit operation and implementation as simple as possible (specially for its use case) it was okay to be like this. (zos actually when it does a stop, it keep pulling the status until it goes down or send a SIGKILL via zinit if needed)

We can take a look what is needed to be done to support this functionality internally

**Comment by ashraffouda** [comment]
done here https://github.com/threefoldtech/zinit/pull/55/files
